Repository Sangwona/studyboard, pull requests merged in 2025-02, with the labels that each got.

#4 database connection & basic model & postAPI
  app.py
  config.py
  database.py
  models.py
  routes.py
  test_api.py
Labels: enhancement

#5 Post Components and User Icon
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Post/Post.jsx
  frontend/src/components/Post/PostContent.jsx
  frontend/src/components/Post/PostHeader.jsx
  frontend/src/components/User/UserIcon.jsx
  frontend/src/index.css
  frontend/src/styles/PostHeader.css
  frontend/src/styles/UserIcon.css
Labels: enhancement, good first issue

#8 requirements txt file reset
  HOW TO START.md
  requirements.txt
Labels: bug

#9 CORS Setting
  app.py
  requirements.txt
Labels: bug

#20 pre-flight option added for CORS
  app.py
Labels: bug

#21 CORS setting2
  app.py
Labels: bug

#25 React serving, making ONE SERVER and organizing folder to backend
  Procfile
  backend/app.py
  backend/auth_routes.py
  backend/config.py
  backend/database.py
  backend/models.py
  backend/requirements.txt
  backend/routes.py
  backend/test_api.py
  frontend/src/components/Pages/Home.jsx
  frontend/src/components/Pages/Login.jsx
  frontend/src/components/Pages/SignUp.jsx
  frontend/src/components/Pages/WriteForm.jsx
  frontend/src/components/Post/Post.jsx
  railway.json
Labels: enhancement
